# Generated by Django 3.2.25 on 2026-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='enrollment_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
