# Generated by Django 3.2.25 on 2026-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260608_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('password_change', 'Password Change')], max_length=50),
        ),
    ]
