# Generated by Django 3.2.25 on 2026-06-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260609_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
