# Generated by Codex on 2026-06-09

from django.conf import settings
from django.db import migrations, models


def copy_checkin_manager_to_checkin_managers(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    for event in Event.objects.exclude(checkin_manager=None).iterator():
        event.checkin_managers.add(event.checkin_manager_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_checkin_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_managers',
            field=models.ManyToManyField(blank=True, related_name='managed_events_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_checkin_manager_to_checkin_managers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='event',
            name='checkin_manager',
        ),
        migrations.AlterField(
            model_name='event',
            name='checkin_managers',
            field=models.ManyToManyField(blank=True, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
