# Generated by Django 3.2.25 on 2026-06-09 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contest_submission_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('series_type', models.CharField(choices=[('training', '训练'), ('lecture', '讲座'), ('sharing', '分享会'), ('other', '其他')], default='training', max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_event_count', models.PositiveSmallIntegerField(default=10)),
                ('required_checkins_for_rating', models.PositiveSmallIntegerField(default=1)),
                ('rating_enabled', models.BooleanField(default=False)),
                ('rating_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系列活动',
                'verbose_name_plural': '系列活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSeriesCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_checkin_count', models.PositiveSmallIntegerField(default=0)),
                ('is_completed_for_rating', models.BooleanField(default=False)),
                ('rating_delta', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_counted_checkin_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='series_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseriescompletion',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_completions', to='core.memberprofile'),
        ),
        migrations.AddField(
            model_name='eventseriescompletion',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.eventseries'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_event_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.eventseries'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'series_order'), name='unique_series_order'),
        ),
        migrations.AddConstraint(
            model_name='eventseriescompletion',
            constraint=models.UniqueConstraint(fields=('member', 'series'), name='unique_member_series_completion'),
        ),
    ]
