# Generated by Django 3.2.25 on 2026-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_member_team_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='team_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
