# Generated by Django 3.2.25 on 2026-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contestsubmission_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=20),
        ),
    ]
