# Generated by Django 3.2.25 on 2026-06-09 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_contestsubmission_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIntegritySanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('contest_no_show', '报名后缺席比赛'), ('serious_rule_violation', '活动中严重违反规则'), ('other', '其他')], default='other', max_length=40)),
                ('member_reason', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_integrity_sanctions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_sanctions', to='core.memberprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_integrity_sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
    ]
