# Generated by Django 3.2.25 on 2026-06-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contest_use_default_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestresult',
            name='result_tier',
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='result_tier',
        ),
    ]
