# Generated by Django 3.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20260611_1149'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_series_order',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(
                condition=models.Q(('series__isnull', False), ('series_order__isnull', False)),
                fields=('series', 'series_order'),
                name='unique_series_order',
            ),
        ),
    ]
